export { Table } from '@chakra-ui/react'
export * from './TableCaption'
export * from './Tbody'
export * from './Td'
export * from './Tfoot'
export * from './Th'
export * from './Thead'
export * from './Tr'
